// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz1fY9UqL1qGXw-l5oFzy8Pkgozb__KSU',
    appId: '1:432219406370:web:5f1483936f144fc8ddca7b',
    messagingSenderId: '432219406370',
    projectId: 'mybucks-5bdab',
    authDomain: 'mybucks-5bdab.firebaseapp.com',
    storageBucket: 'mybucks-5bdab.appspot.com',
    measurementId: 'G-ZVK654JRQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxG9Y88WpPGCTCZBy98Pq4g30qqVMWGCA',
    appId: '1:432219406370:android:7aa7e21c6cdaefc3ddca7b',
    messagingSenderId: '432219406370',
    projectId: 'mybucks-5bdab',
    storageBucket: 'mybucks-5bdab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_JExKAauVqKkB3UqE0ABgDkQhtIHQJRY',
    appId: '1:432219406370:ios:07480fd7bd864ca6ddca7b',
    messagingSenderId: '432219406370',
    projectId: 'mybucks-5bdab',
    storageBucket: 'mybucks-5bdab.appspot.com',
    iosClientId: '432219406370-ta00d4ak2kal7d0jbprd81e00dmhphga.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybucks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_JExKAauVqKkB3UqE0ABgDkQhtIHQJRY',
    appId: '1:432219406370:ios:ad27c5549403e0d6ddca7b',
    messagingSenderId: '432219406370',
    projectId: 'mybucks-5bdab',
    storageBucket: 'mybucks-5bdab.appspot.com',
    iosClientId: '432219406370-fb9b3mblu5lm58l28b5kdmgqfcc54h7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybucks.RunnerTests',
  );
}
